font:
  normal:
    family: MesloLGS NF
    style: Regular
  bold:
    family: MesloLGS NF
    style: Bold
  italic:
    family: MesloLGS NF
    style: Italic
  bold_italic:
    family: MesloLGS NF
    style: Bold Italic
  size: 11
# VSCode's integrated terminal default colors
# Primary and dimmed colors needed
colors:
  # Default colors
  primary:
    background: '#1e1e1e' #Background from Dark Theme
    foreground: '#cccccc'
  # Selection colors
  selection:
    text: CellForeground
    background: '#565656'
  # Normal colors
  normal:
    black:   '#000000'
    red:     '#cd3131'
    green:   '#0dbc79'
    yellow:  '#e5e510'
    blue:    '#2472c8'
    magenta: '#bc3fbc'
    cyan:    '#11a8cd'
    white:   '#e5e5e5'
  # Bright colors
  bright:
    black:   '#666666'
    red:     '#f14c4c'
    green:   '#23d18b'
    yellow:  '#f5f543'
    blue:    '#3b8eea'
    magenta: '#d670d6'
    cyan:    '#29b8db'
    white:   '#e5e5e5'
key_bindings:
  - { key: V,        mods: Control,           action: Paste          }
  - { key: PageUp,                            action: ScrollPageUp   }
  - { key: PageDown,                          action: ScrollPageDown }
